---
name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@v4"
            - uses: "pnpm/action-setup@v3.0.0"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v4"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - run: "make install"
            - run: "make lint"
