---
name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f"
            - uses: "pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d"
              with:
                  version: "latest"
            - uses: "actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - run: "make install"
            - run: "make lint"
