---
name: "sast"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"
    schedule:
        - cron: "0 0 15 * *"

jobs:
    snyk:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - uses: "pnpm/action-setup@v2.0.1"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v4"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "snyk/actions/setup@master"
            - run: "make install"
            - run: "snyk test --all-projects --detection-depth=1"
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
