---
name: "sast"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"
    schedule:
        - cron: "0 0 15 * *"

permissions: "read-all"

jobs:
    snyk:
        permissions:
            contents: "read"
            security-events: "write"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
            - uses: "pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d"
              with:
                  version: "latest"
            - uses: "actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "snyk/actions/setup@b98d498629f1c368650224d6d212bf7dfa89e4bf"
            - run: "make install"
            - run: "snyk test --all-projects --detection-depth=1 --sarif-file-output=snyk.sarif"
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            - uses: "github/codeql-action/upload-sarif@ccf74c947955fd1cf117aef6a0e4e66191ef6f61"
              with:
                  sarif_file: "snyk.sarif"
